name: Profile

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  runner-job:
    runs-on: ubuntu-latest

    # Service containers to run with `runner-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432

    steps:
      - name: checkout project
        uses: actions/checkout@v3

      - name: go setup
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.1
          check-latest: true

      - name: go mod tidy
        run: go mod tidy

      - name: lint
        uses: golangci/golangci-lint-action@v3

      - name: test
        run: go test ./... -race -count=1 -cover
